### ISSUE TITLE
IoTDMClientLib for netstandard2.0

### ISSUE THREAD

**Issue by tymtam2** [ms-iot/iot-core-azure-dm-client#275]
Microsoft.Azure.Devices.Client supports netstandard2.0 and seems not to IoTDMClientLib is a Universal Windows lib.

Is there a plan at all (long or short term) to make  IoTDMClientLib a not a UWP library?

**Comment by gmileka** [comment]
Hi tymtam2,

There is no plan currently to provide a non-UWP version of IoTDMClientLib. The app model on IoT Core is mostly UWP.

Do you need to access the same functionality from a non-UWP?

We are considering releasing a standalone DM service that does not rely on the UWP app at all. This is feasible now because we can make sure of the IoT Hub modules - which allows multiple connections from the same physical device to target the same logical device on IoT Hub (though different modules).

I'll close this bug - but feel free to re-open to continue the conversation.

**Comment by tymtam2** [comment]
Where can I read about the modules? We're currently use 2 ids where we probably use one.
